# Site settings
title: Travelog
subtitle: "Journal of [name]"
email: your-email@domain.com
description: "Sed luctus vitae augue vitae dignissim. Aenean in iaculis orci. Praesent sagittis nulla sit amet nibh feugiat iaculis."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: "[name]"
github_username:  "[name]"
instagram_username: "[name]"

# Build settings
markdown: kramdown
permalink: pretty
